# Generated by Django 5.0.4 on 2024-04-22 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_project_project_name_bug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bug',
            name='date_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.BooleanField(choices=[('Open', 'True'), ('Closed', 'Closed')], default='Open'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bugs', to=settings.AUTH_USER_MODEL),
        ),
    ]
