# Generated by Django 5.0.4 on 2024-04-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_bug_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='resolve',
            field=models.BinaryField(default=False),
        ),
    ]
