# Generated by Django 5.0.4 on 2024-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_bug_resolve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='resolve',
            field=models.BooleanField(default=False),
        ),
    ]
